### ISSUE TITLE
Suction cup 3D models

### ISSUE THREAD

**Issue by ghost** [kikaitachi/naminukas#2]
Hello,
I've looked a lot through the project website and found out that you've made 2 different prototypes of 3D printed suction cups. The most interesting to me seems to be this version: https://naminukas.kikaitachi.com/blog/2020-09-06/rubber-foam-suction-cup
Could you please share the 3d models for this? It would be great to look into ways of making the robot available in countries where it's hard to get the suction cups and ways of making the robot cheaper.

**Comment by kikaitachi** [comment]
[OpenSCAD](https://www.openscad.org/) model is in this file https://github.com/kikaitachi/naminukas/blob/master/3d-models/suction-cup-connector.scad. It uses a lot of parameters from `dimensions.scad`. For thread generation https://github.com/adrianschlatter/threadlib library is used. Please let me know if you find an easy way to smoothly cut neoprene foam :)

**Comment by ghost** [comment]
Oh my bad, I thought this file would just be a connector between the pipe and a commercial suction cup
Freezing is helpful for cutting rubber but I don't know what temps are necessary for neoprene
Thanks a lot
